vrs_config: /etc/default/openvswitch
vsp_k8s_dir: /usr/share/vsp-k8s
nuage_plugin_crt_dir : /usr/share/vsp-k8s
vsp_k8s_yaml: "{{ vsp_k8s_dir }}/vsp-k8s.yaml"
nuage_master_cluster_hostname: "{{ groups['masters'][0] }}"
nuage_mon_rest_server_port: "{{ nuage_monitor_rest_server_port | default('9443') }}"
nuage_mon_rest_server_url: "https://{{ nuage_master_cluster_hostname }}:{{ nuage_mon_rest_server_port }}"
docker_bridge: "{{ nuage_docker_bridge | default('docker0') }}"
rest_client_cert: "{{ vsp_k8s_dir }}/nuageMonClient.crt"
rest_client_key: "{{ vsp_k8s_dir }}/nuageMonClient.key"
rest_server_ca_cert: "{{ vsp_k8s_dir }}/nuageMonCA.crt"
vport_mtu: "{{ nuage_interface_mtu | default('1460') }}"
plugin_log_level: "{{ nuage_plugin_log_level | default('err') }}"

svc_pat_tap_ip: "{{ nuage_svc_pat_tap_ip | default('169.254.3.3') }}"
svc_pat_tap_dev: "{{ nuage_svc_pat_tap_dev | default('svc-pat-tap') }}"
svc_pat_tap_route_cmd: "route add {{nuage_cluster_nw_cidr }} via {{ svc_pat_tap_ip }} dev {{ svc_pat_tap_dev }}"
svc_pat_tap_route_file: "/etc/sysconfig/network-scripts/route-{{ svc_pat_tap_dev }}"

nuage_plugin_rest_client_crt_dir: "{{ nuage_ca_master_crt_dir }}/{{ ansible_nodename }}"
nuage_ca_master_plugin_key: "{{ nuage_plugin_rest_client_crt_dir }}/nuageMonClient.key"
nuage_ca_master_plugin_crt: "{{ nuage_plugin_rest_client_crt_dir }}/nuageMonClient.crt" 
kubelet_service_file: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
nuage_plugin_kubelet_args: "Environment=\"KUBELET_NETWORK_ARGS=--network-plugin=vsp-k8s --network-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/net/exec/\""
kubelet_execstart: "ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS"
