---
- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: s
  changed_when: false
  always_run: yes

- name: Init the is_atomic fact
  set_fact:
    is_atomic: false

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.stat.exists

- name: Set docker config file directory
  set_fact:
    docker_config_dir: "/etc/sysconfig"

- name: Override docker config file directory for Debian
  set_fact:
    docker_config_dir: "/etc/default"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Determine if has rpm
  stat: path=/usr/bin/rpm
  register: s
  changed_when: false
  always_run: yes

- name: Init the has_rpm fact
  set_fact:
    has_rpm: false

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: s.stat.exists

- name: Init the has_firewalld fact
  set_fact:
    has_firewalld: false

- name: Init the has_iptables fact
  set_fact:
    has_iptables: false

# collect information about what packages are installed
- include: rpm.yml
  when: has_rpm

- include: fedora-install.yml
  when: not is_atomic and ansible_distribution == "Fedora"
