# stop services
- name: stop kubelet
  service: name=kubelet state=stopped

- name: stop docker
  service: name=docker state=stopped

- name: stop netplugin
  service: name=netplugin state=stopped

# perform clean up
- name: delete contivk8s log file
  file: path=/var/log/contivk8s.log state=absent

- name: copy clean up script
  copy: src=contiv_agent_clean.sh dest=/usr/bin/contiv_agent_clean.sh mode=0755

- name: clean up
  shell: contiv_agent_clean.sh || true

# set up services
- name: ensure pluginDir exists
  file: path=/usr/libexec/kubernetes/kubelet-plugins/net/exec recurse=yes state=directory

- name: copy contiv cni conf file
  copy: src=contiv_cni.conf dest=/usr/libexec/kubernetes/kubelet-plugins/net/exec/contiv_cni.conf

- name: ensure cni bin dir exists
  file: path=/opt/cni/bin recurse=yes state=directory

- name: copy contiv cni exec file
  copy: src={{ contiv_bin_path }}/contivk8s dest=/opt/cni/bin/contivk8s.bin mode=0755

- name: ensure contiv config directory exists
  file: path=/opt/contiv/config recurse=yes state=directory

- name: setup config for the contiv cni plugin
  template: src=contiv.cfg.j2 dest=/opt/contiv/config/contiv.json

- name: copy netplugin exec file
  copy: src={{ contiv_bin_path }}/netplugin dest=/usr/bin/netplugin mode=0755

- name: copy environment file for netplugin
  template: src=netplugin.j2 dest=/etc/default/netplugin mode=0644

- name: copy systemd units for netplugin
  copy: src=netplugin.service dest=/etc/systemd/system/netplugin.service

# start services
- name: start ovs service
  service: "name=openvswitch enabled=yes state=started"
  when: ansible_os_family == "RedHat"

- name: setup ovs
  shell: "ovs-vsctl set-manager {{ item }}"
  with_items:
    - "tcp:127.0.0.1:6640"
    - "ptcp:6640"

- name: start netplugin
  service: name=netplugin state=started

- name: start docker
  service: name=docker state=started

- name: start kubelet
  service: name=kubelet state=started

