---
- include: config.yml

- include: client.yml
  when: inventory_hostname in groups['masters'] + groups['nodes']

- include: coreos.yml
  when: ansible_lsb.id == "CoreOS"

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables

- name: Enable flannel
  service: name=flanneld enabled=yes

- name: Start flannel
  service: name=flanneld state=started
  register: flannel_started
  notify:
    - restart docker
