---
- name: Install openssl for easy-rsa stuff
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
    - openssl
    - curl
  when: not is_atomic and not is_coreos

#- name: Get create ca cert script from Kubernetes
#  get_url:
#    url=https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/saltbase/salt/generate-cert/make-ca-cert.sh
#    dest={{ kube_script_dir }}/make-ca-cert.sh mode=0500
#    force=yes

- name: HACK | overwrite make-ca-cert.sh from local copy
  copy:
    src: make-ca-cert.sh
    dest: "{{ kube_script_dir }}"
    mode: "0500"
  changed_when: false

- name: Run create cert script on master
  command:
    "{{ kube_script_dir }}/make-ca-cert.sh"
  args:
    creates: "{{ kube_cert_dir }}/server.crt"
  environment:
    MASTER_IP: "{% for host in groups['masters'] %}{{ hostvars[host]['kube_cert_ip'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    MASTERS: "{{ groups['masters']|join(',') }}"
    DNS_DOMAIN: "{{ dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"
    CERT_DIR: "{{ kube_cert_dir }}"
    CERT_GROUP: "{{ kube_cert_group }}"
    HTTP_PROXY: "{{ http_proxy|default('') }}"
    HTTPS_PROXY: "{{ https_proxy|default('') }}"
    CLUSTER_HOSTNAME: "{{ master_cluster_hostname|default('') }}"
    CLUSTER_PUBLIC_HOSTNAME: "{{ master_cluster_public_hostname|default('') }}"
    KUBE_CERT_KEEP_CA: "{{ kube_cert_keep_ca | default(false) | lower }}"

- name: Verify certificate permissions
  file:
    path={{ item }}
    group={{ kube_cert_group }}
    owner=kube
    mode=0440
  with_items:
    - "{{ kube_cert_dir }}/ca.crt"
    - "{{ kube_cert_dir }}/server.crt"
    - "{{ kube_cert_dir }}/server.key"
    - "{{ kube_cert_dir }}/kubecfg.crt"
    - "{{ kube_cert_dir }}/kubecfg.key"

- name: Check CA private key permissions if kube_cert_keep_ca is set to "true"
  file:
    path: "{{ kube_cert_dir }}/ca.key"
    group: "{{ kube_cert_group }}"
    owner: kube
    mode: 0440
  when: kube_cert_keep_ca | default(false)
