---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Update {{ kube_script_dir }} if this is atomic
  set_fact:
    kube_script_dir: "/usr/local/libexec/kubernetes"
  when: is_atomic and kube_script_dir == "/usr/libexec/kubernetes"

- name: Initialize the python_bin fact
  set_fact:
    python_bin: "python"

- name: Update facts if this is CoreOS
  set_fact:
    bin_dir: "/opt/bin"
    kube_script_dir: "/opt/bin/kubernetes"
    python_bin: "/opt/bin/python"
  when: is_coreos

- name: Create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory

- name: Create manifests directory
  file: path={{ kube_manifest_dir }} state=directory mode=0755

- name: Create standby-manifests directory
  file: path={{ kube_standby_manifest_dir }} state=directory mode=0755

- name: Create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: Create bin dir
  file: path={{ bin_dir }} state=directory

- name: write the global config file
  template: src=config.j2 dest={{ kube_config_dir }}/config
  notify:
    - restart daemons

- include: download_bins.yml
  when: is_coreos

- include: secrets.yml
  tags:
    secrets
