---
- name: KUBE-DASH | Assures {{ kube_addons_dir }}/kube-dash dir exists
  file: path={{ kube_addons_dir }}/kube-dash state=directory

- name: KUBE-DASH | Download kube-dash files from Kubernetes repo
  get_url:
    url=https://raw.githubusercontent.com/kubernetes/kubedash/master/deploy/{{ item }}
    dest="{{ kube_addons_dir }}/kube-dash/"
    force=yes
    validate_certs=False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
  with_items:
    - kube-dash-rc.yaml
    - kube-dash-svc.yaml
